size(chihuahua, small).
place(chihuahua, apartment).
place(chihuahua, small).
place(chihuahua, large).
kids(chihuahua, no).
allergies(chihuahua, no).
pets(chihuahua, no).
dogs(chihuahua, yes).
outdoors(chihuahua, 1).
outdoors(chihuahua, 2).
outdoors(chihuahua, 3).

size(golden_retriever, large).
place(golden_retriever, large).
kids(golden_retriever, yes).
kids(golden_retriever, no).
allergies(golden_retriever, no).
pets(golden_retriever, yes).
pets(golden_retriever, no).
dogs(golden_retriever, yes).
dogs(golden_retriever, no).
outdoors(golden_retriever, 3).
outdoors(golden_retriever, 4).
outdoors(golden_retriever, 5).

size(labrador, medium).
place(labrador, large).
kids(labrador, yes).
kids(labrador, no).
allergies(labrador, no).
pets(labrador, yes).
pets(labrador, no).
dogs(labrador, yes).
dogs(labrador, no).
outdoors(labrador, 3).
outdoors(labrador, 4).
outdoors(labrador, 5).

size(german_shepherd, medium).
place(german_shepherd, small).
place(german_shepherd, large).
kids(german_shepherd, no).
kids(german_shepherd, yes).
allergies(german_shepherd, no).
pets(german_shepherd, no).
dogs(german_shepherd, yes).
outdoors(german_shepherd, 3).
outdoors(german_shepherd, 4).
outdoors(german_shepherd, 5).

size(husky, large).
place(husky, large).
kids(husky, yes).
kids(husky, no).
allergies(husky, no).
pets(husky, yes).
pets(husky, no).
dogs(husky, yes).
outdoors(husky, 3).
outdoors(husky, 4).
outdoors(husky, 5).

size(beagle, small).
place(beagle, small).
place(beagle, large).
kids(beagle, yes).
kids(beagle, no).
allergies(beagle, no).
pets(beagle, yes).
pets(beagle, no).
dogs(beagle, yes).
outdoors(beagle, 3).
outdoors(beagle, 4).
outdoors(beagle, 5).

size(shiba_inu, medium).
place(shiba_inu, apartment).
place(shiba_inu, small).
place(shiba_inu, large).
kids(shiba_inu, no).
allergies(shiba_inu, no).
pets(shiba_inu, no).
dogs(shiba_inu, yes).
dogs(shiba_inu, no).
outdoors(shiba_inu, 1).
outdoors(shiba_inu, 2).
outdoors(shiba_inu, 3).

size(bulldog, medium).
place(bulldog, large).
kids(bulldog, yes).
kids(bulldog, no).
allergies(bulldog, no).
pets(bulldog, no).
dogs(bulldog, yes).
dogs(bulldog, no).
outdoors(bulldog, 3).
outdoors(bulldog, 4).
outdoors(bulldog, 5).

size(pug, small).
place(pug, apartment).
place(pug, small).
place(pug, large).
kids(pug, yes).
kids(pug, no).
allergies(pug, no).
pets(pug, no).
pets(pug, yes).
dogs(pug, yes).
dogs(pug, no).
outdoors(pug, 1).
outdoors(pug, 2).
outdoors(pug, 3).

size(doberman, large).
place(doberman, small).
place(doberman, large).
kids(doberman, no).
allergies(doberman, no).
pets(doberman, no).
dogs(doberman, yes).
outdoors(doberman, 3).
outdoors(doberman, 4).
outdoors(doberman, 5).

size(terrier, small).
place(terrier, apartment).
place(terrier, small).
place(terrier, large).
kids(terrier, yes).
kids(terrier, no).
allergies(terrier, yes).
allergies(terrier, no).
pets(terrier, no).
dogs(terrier, yes).
dogs(terrier, no).
outdoors(terrier, 3).
outdoors(terrier, 4).
outdoors(terrier, 5).

size(shih_tzu, small).
place(shih_tzu, apartment).
place(shih_tzu, small).
place(shih_tzu, large).
kids(shih_tzu, yes).
kids(shih_tzu, no).
allergies(shih_tzu, yes).
allergies(shih_tzu, no).
pets(shih_tzu, yes).
pets(shih_tzu, no).
dogs(shih_tzu, yes).
dogs(shih_tzu, no).
outdoors(shih_tzu, 1).
outdoors(shih_tzu, 2).
outdoors(shih_tzu, 3).

size(poodle, medium).
place(poodle, apartment).
place(poodle, small).
place(poodle, large).
kids(poodle, yes).
kids(poodle, no).
allergies(poodle, yes).
allergies(poodle, no).
pets(poodle, yes).
pets(poodle, no).
dogs(poodle, yes).
dogs(poodle, no).
outdoors(poodle, 3).
outdoors(poodle, 4).
outdoors(poodle, 5).

#include 'PawLog.pl'.